---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbs-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: jdcsp-cbs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbs-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: jdcsp-cbs-sc