---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufs-demo-app
spec:
  selector:
    matchLabels:
      name: ufs-demo-app
  replicas: 2
  template:
    metadata:
      labels:
        name: ufs-demo-app
    spec:
      containers:
        - name: demo
          image: harbor.jdts.com/centos/jdcsp-csi-demo-app:v1.0
          volumeMounts:
            - name: volume-1
              mountPath: /data1
      volumes:
        - name: volume-1
          persistentVolumeClaim:
            claimName: ufs-pvc-1
